server:
  port: 8080

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/books_db
      username: myuser
      password: secret

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public
